import React from 'react';
import { AlertTriangle, CheckCircle2, Info, ArrowRight } from 'lucide-react';
import RiskMeter from './RiskMeter';

export default function PredictionResult({ result }) {
  if (!result) return null;

  const { prediction, backlog, risk_percentage, inputs } = result;

  return (
    <div className="p-6 lg:p-8 rounded-2xl bg-slate-900/80 backdrop-blur border border-slate-800/80 space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <span className="text-xs font-bold uppercase tracking-wider text-slate-400">Prediction Output</span>
          <h2 className="text-2xl font-black text-white tracking-tight mt-0.5">
            {backlog ? 'BACKLOG RISK DETECTED' : 'LOW BACKLOG RISK'}
          </h2>
        </div>
        <div className={`p-3 rounded-2xl ${backlog ? 'bg-rose-500/10 text-rose-400 border border-rose-500/30' : 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/30'}`}>
          {backlog ? <AlertTriangle className="w-6 h-6" /> : <CheckCircle2 className="w-6 h-6" />}
        </div>
      </div>

      {/* Risk Meter Visual */}
      <RiskMeter riskPercentage={risk_percentage} isBacklog={backlog} />

      {/* Submitted Inputs Summary */}
      <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800 space-y-3">
        <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider">Submitted Inputs</h4>
        <div className="grid grid-cols-3 gap-2 text-center">
          <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
            <span className="block text-[11px] text-slate-400">Study Hours</span>
            <span className="text-sm font-bold text-white mt-0.5 block">{inputs.weekly_self_study_hours} hrs/wk</span>
          </div>
          <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
            <span className="block text-[11px] text-slate-400">Attendance</span>
            <span className="text-sm font-bold text-white mt-0.5 block">{inputs.attendance_percentage}%</span>
          </div>
          <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
            <span className="block text-[11px] text-slate-400">Participation</span>
            <span className="text-sm font-bold text-white mt-0.5 block">{inputs.class_participation}</span>
          </div>
        </div>
      </div>

      {/* Academic Advice Banner */}
      <div className={`p-4 rounded-xl border flex items-start gap-3 ${
        backlog 
          ? 'bg-rose-500/10 border-rose-500/30 text-rose-200' 
          : 'bg-emerald-500/10 border-emerald-500/30 text-emerald-200'
      }`}>
        <Info className="w-5 h-5 shrink-0 mt-0.5" />
        <div className="text-xs leading-relaxed space-y-1">
          <p className="font-bold">
            {backlog 
              ? 'Academic Alert & Recommendations:' 
              : 'Positive Academic Status:'}
          </p>
          <p>
            {backlog
              ? 'The model has identified this student as being at backlog risk. Consider improving attendance, study consistency, and class participation.'
              : 'The model currently predicts no backlog risk based on the provided inputs. Maintain steady study habits and class attendance.'}
          </p>
          <p className="text-[10px] opacity-75 pt-1">
            * Note: Predictions are statistical estimates generated by a DecisionTree model (max_depth=5) trained on student performance data.
          </p>
        </div>
      </div>
    </div>
  );
}
